### ISSUE TITLE
When loss is "ssim", NaN show up.

### ISSUE THREAD

**Issue by Ricky-Wen-4-Me** [magdalena-wysocki/ultra-nerf#5]
First, I want to apologize for my weak English presentation.
Second, I want to thank you guys for your wonderful job.
I read your paper, it is very impressive work.
but when I ran it, something wrong happened, and I am not a master of Python or TensorFlow.

Traceback (most recent call last):
  File "run_ultra_nerf.py", line 724, in <module>
    train()
  File "run_ultra_nerf.py", line 585, in train
    retraw=True, **render_kwargs_train)
  File "run_ultra_nerf.py", line 254, in render_us
    all_ret = batchify_rays(rays, c2w=c2w, chunk=chunk, **kwargs)
  File "run_ultra_nerf.py", line 218, in batchify_rays
    ret = render_rays_us(rays_flat[i:i + chunk], **kwargs)
  File "run_ultra_nerf.py", line 209, in render_rays_us
    tf.debugging.check_numerics(ret[k], 'output {}'.format(k))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1006, in check_numerics
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: output intensity_map : Tensor had NaN values [Op:CheckNumerics]

here is my environment :
Ubuntu 22.04.3 LTS
NVIDIA Corporation GA102 [GeForce RTX 3090] 
image: nvcr.io/nvidia/tensorflow:20.01-tf1-py3
(because of the model of GPU, to prevent the "blas gemm launch failed" error, I use docker to deal with everything.)
in docker : 
CUDA 10.2

and I run this code below :
python run_ultra_nerf.py --config conf_us.txt --expname ssim_improv --n_iters 1000000 --loss ssim --i_embed_gauss 0 --i_img 1000 --i_print 2000  --i_weights 1000 --i_video 2000 --lrate 5e-6 --N_rand 1024 --ft_path logs/synthetic_200k/model_200000.npy
(the original one at README.md made every layer's gradient go to "NaN")

I don't know what happened to this situation, could please anyone do me a favor to overcome this problem?

**Comment by Ricky-Wen-4-Me** [comment]
okay, I solved the problem.
As a result, I need to execute the following additional instructions:
pip install nvidia-pyindex
pip install nvidia-tensorflow
The 'NaN' problem would be solved magically.
